configVersion: 1.0 # 不要修改此项

# 语言设置，可选 'zh' 或 'en'
language: en

# 剩余飞行时间消息，{time} 为剩余飞行时间（单位：秒）。
flyTimeMessage: "Remaining flight time: {time} seconds"
#flyTimeMessage: "剩余飞行时间: {time} 秒"

# 飞行时间耗尽后是否允许掉落伤害
fallDamageAfterFlyTimeExpired: false

combat:
  disableFly: true # 当玩家处于战斗状态时是否关闭飞行

# 存储类型: 可选 'yaml', 'sqlite' 或 'mysql'
storage:
  type: sqlite

# SQLite 数据库配置（仅在 storage.type 为 'sqlite' 时使用）
sqlite:
  database: "data.db"

# MySQL 数据库配置（仅在 storage.type 为 'mysql' 时使用）
mysql:
  host: "localhost"
  port: 3306
  database: "xyfly"
  username: "root"
  password: "password"