# Xyfly 插件配置文件

# 语言设置
language: en

# 存储类型: 可选 'yaml' 或 'sqlite，默认sqlite'
storage:
  type: sqlite

# 剩余飞行时间消息
flyTimeMessage: "剩余飞行时间: {time} 秒"

# 飞行时间耗尽后是否允许掉落伤害，默认为 false
fallDamageAfterFlyTimeExpired: false

# SQLite 数据库配置（仅在 storage.type 为 'sqlite' 时使用）
sqlite:
  database: "data.db"