name: Xyfly
main: xyfly.xyfly.Xyfly
version: 1.0
api-version: 1.21
author: 你的名字
description: 一个允许玩家使用有限飞行时间的插件

commands:
  xyfly:
    description: 管理玩家的飞行时间
    usage: /<command> <on|off|settime|gettime> [玩家] [时间(秒)]
    permission: xyfly.use
    permission-message: 你没有权限使用这个命令！
permissions:
  xyfly.use:
    description: 允许玩家使用/xyfly命令
    default: true
  xyfly.on:
    description: 允许玩家开启飞行模式
    default: op
  xyfly.off:
    description: 允许玩家关闭飞行模式
    default: op
  xyfly.settime:
    description: 允许玩家设置飞行时间
    default: op
  xyfly.gettime:
    description: 允许玩家获取飞行时间
    default: op
